# Proyecto Final 
## Generación y Análisis de Tienda Online

En este proyecto abordaremos la generación de una dataset que simula las ventas en un contexto real de una Tienda Online dedicada al rubro tecnológico, que vende productos como Notebooks, celulares y accesorios.
Una vez generado el dataset, debemos resolver la problemática planteada por la Tienda utilizando herramientas como MySQL para darle formato a los datos y posteriormente Power BI para visualizarlos e interpretarlos.

Tomamos las decisión de realizar la generación de los datos con Python por lo dinámico y práctico que és para crear los datos con todos los aspectos que queríamos que tenga.

## Objetivo

Generar dataset sintético que represente el comportamiento real de venta de un e-commerce.
El dataset incluirá:
* Clientes
* Productos
* Ventas
* Métodos de Pago
* Categorías

La problemática será esfocada a:
* Control de Stock
* Segmentación de Clientes
* Identificación de los mejores productos

#### Librerias utilizadas para generación y manipulación del dataset

In [1]:
# Librerias estándar
import random
import calendar
import unicodedata
from datetime import datetime, timedelta

# Librerias de análisis de datos
import pandas as pd
import numpy as np

# Elige los mismo valores siempre en las funciones randoms
random.seed(42)
np.random.seed(42)

#### Período de Análisis

Suponemos el inicio de las ventas en el año 2024 y el período de análisis hasta 2025.

(2024 - 2025)

In [2]:
""" Definimos el rango de fecha que tendremos para analizar ventas """

fecha_inicio = datetime.strptime("2024-1-01","%Y-%m-%d") #formato año-mes-dia
fecha_fin = datetime.strptime("2025-12-31","%Y-%m-%d")

#### Definición de datos para Clientes 

Cargamos en diferentes listas, datos aleatorios correspondientes a datos de un cliente para luego poder seleccionarlos con funciones random (selección de elementos de la lista al azar).
La función random la usaremos de dos maneras, con influencia de pesos (cuáles datos tienen mas probabilidad de salir) y sin influencia de ellos.

A continuación se detallan datos de:

* Nombres y apellidos
* Terminaciones de mail
* Localidades en listas

In [3]:
nombres = ["Ana", "Sofia", "Maria", "Lucia", "Valentina", "Camila", "Martina", "Julieta","Paula", "Florencia", "Carolina", "Victoria", 
           "Agustina", "Milagros","Rocio", "Micaela", "Natalia", "Gabriela", "Daniela", "Laura","Romina", "Belen", "Noelia", "Andrea",
           "Claudia", "Veronica","Silvia", "Patricia", "Monica", "Alejandra", "Mariana", "Lorena","Cecilia", "Pilar", "Abril", "Bianca",
           "Constanza", "Renata","Malena", "Antonella", "Brenda", "Candelaria", "Jazmin", "Ailén","Sol", "Lara", "Candela", "Ariana",
           "Nadia", "Yamila","Tamara", "Estefania", "Juliana", "Ines", "Olivia", "Alma","Francesca", "Isabella", "Emma", "Zoe", "Mara",
           "Helena","Elena", "Irene", "Rebeca", "Amparo", "Alicia", "Clara", "Juan", "Carlos", "Pedro", "Lucas", "Mateo", "Santiago",
           "Nicolas","Martin", "Agustin", "Franco", "Tomas", "Facundo", "Joaquin","Sebastian", "Gonzalo", "Diego", "Pablo", "Alejandro",
           "Marcos","Ricardo", "Federico", "Emiliano", "Leonardo", "Hernan", "Matias","Ezequiel", "Adrian", "Cristian", "Julian", "Ignacio",
           "Bruno","German", "Ivan", "Axel", "Kevin", "Brian", "Alan", "Dario","Raul", "Oscar", "Victor", "Guillermo", "Rodrigo", "Esteban",
           "Andres", "Alberto", "Ramon", "Hugo", "Walter", "Miguel","Angel", "Sergio", "Mauricio", "Fernando", "Manuel", "Lautaro","Benjamin",
           "Thiago", "Valentin", "Aaron", "Tobias", "Ulises","Ramiro", "Lisandro", "Matheo", "Bautista", "Gaspar", "Leandro"]
apellidos = ["Gomez", "Perez", "Lopez", "Martinez", "Rodriguez", "Fernandez","Garcia", "Sanchez", "Romero", "Diaz", "Torres", "Ruiz", "Alvarez",
             "Molina", "Suarez", "Castro", "Ortiz", "Silva", "Nunez", "Ramos","Acosta", "Benitez", "Medina", "Herrera", "Aguirre", "Gimenez",
             "Gutierrez", "Pereyra", "Vega", "Rojas", "Luna", "Cabrera","Ibarra", "Farias", "Mendez", "Godoy", "Correa", "Dominguez","Vazquez",
             "Navarro", "Roldan", "Quiroga", "Peralta", "Ponce","Sosa", "Bustos", "Escobar", "Arce", "Villalba", "Ferreyra","Miranda", "Barrios",
             "Carrizo", "Ojeda", "Bravo", "Ayala","Maldonado", "Lucero", "Arias", "Palacios", "Ledesma", "Cruz","Montoya", "Figueroa", "Campos",
             "Rivas", "Rivera", "Franco","Vidal", "Saavedra", "Caceres", "Mansilla", "Bermudez","Santillan", "Toledo", "Quintana", "Serrano",
             "Valdez","Coronel", "Moyano", "Santiago", "Padilla", "Ramos","Carranza", "Reyes", "Bianchi", "Ferrari", "Conti", "Moretti", "Salinas",
             "Villagra", "Cisneros", "Aranda", "Lencina","Zarate", "Benavidez", "Cuevas", "Cardozo", "Tapia","Loyola", "Aguilar", "Ocampo", "Escudero",
             "Barrera","Villarreal", "Zapata", "Granados", "Farina", "Delgado","Olivera", "Sarmiento", "Baez", "Tellez", "Andrada","Salgado", "Amaya",
             "Vallejos", "Lazaro", "Machado","Ceballos", "Lemos", "Carabajal", "Almada", "Villanueva","Riquelme", "Zuniga", "Bustamante", "Cortez",
             "Duarte","Galarza", "Monzon", "Funes", "Villar", "Arrieta","Cano", "Altamirano", "Benavente", "Mancini", "Pizarro"]
dominios = ['@gmail.com', '@hotmail.com', '@yahoo.com', '@outlook.com']
localidades_buenos_aires = [
    "La Plata", "Mar del Plata", "Bahia Blanca", "Tandil", "Olavarria","Azul", "Pergamino", "Junin", "San Nicolas", "Zarate",
    "Campana", "Lujan", "Mercedes", "Chivilcoy", "Necochea","Miramar", "Balcarce", "Tres Arroyos", "Pehuajo", "9 de Julio",
    "Bragado", "Dolores", "Pinamar", "Villa Gesell", "San Pedro"
]
localidades_cordoba = [
    "Cordoba", "Villa Carlos Paz", "Rio Cuarto", "Villa Maria","San Francisco", "Alta Gracia", "Jesus Maria", "Cosquin",
    "La Falda", "Villa Allende", "Bell Ville", "Marcos Juarez","Rio Tercero", "Dean Funes", "Capilla del Monte"
]
localidades_santa_fe = [
    "Rosario", "Santa Fe", "Rafaela", "Venado Tuerto","Reconquista", "Villa Gobernador Galvez", "Esperanza",
    "Santo Tome", "San Lorenzo", "Casilda","Firmat", "San Justo"
]
localidades_mendoza = [
    "Mendoza", "San Rafael", "Godoy Cruz", "Guaymallen","Las Heras", "Lujan de Cuyo", "Maipu", "Tunuyan","San Martin", "Malargue"
]
localidades_entre_rios = [
    "Parana", "Concordia", "Gualeguaychu", "Gualeguay","Colon", "Victoria", "Chajari", "La Paz"
]
localidades_tucuman = [
    "San Miguel de Tucuman", "Tafi Viejo", "Concepcion","Yerba Buena", "Monteros", "Aguilares"
]
localidades_salta = [
    "Salta", "Oran", "Tartagal","Cafayate", "Rosario de la Frontera", "Metan"
]
localidades_neuquen = [
    "Neuquen", "Plottier", "Cipolletti","Cutral Co", "Zapala", "San Martin de los Andes"
]
localidades_rio_negro = [
    "Viedma", "Bariloche", "Cipolletti","General Roca", "Allen", "El Bolson"
]
localidades_chubut = [
    "Rawson", "Trelew", "Puerto Madryn","Comodoro Rivadavia", "Esquel"
]
localidades = {
    "Buenos Aires": localidades_buenos_aires,
    "Cordoba": localidades_cordoba,
    "Santa Fe": localidades_santa_fe,
    "Mendoza": localidades_mendoza,
    "Entre Rios": localidades_entre_rios,
    "Tucuman": localidades_tucuman,
    "Salta": localidades_salta,
    "Neuquen": localidades_neuquen,
    "Rio Negro": localidades_rio_negro,
    "Chubut": localidades_chubut
}

#### Definicón de Métodos de Pago

Se definen los métodos de pago que utiliza la Tienda.
Para cargar cada dato se utiliza la estructura de lista donde cada elemento de la lista es un diccionario con cada "columna" de la tabla que se formará posteriormente.

Usaremos este formato para todas las tablas que vamos a representar.

In [4]:
metodosDePago = [
    { 'idPago' : 1, 'metodo': "Transferencia", 'descripcion': "Pago realizado a traves de una transferencia de fondos entre cuentas bancarias."},
    { 'idPago' : 2, 'metodo': "Tarjeta de Credito", 'descripcion': "Pago con tarjetas emitidas por bancos y financieras, con la opcion de pago a credito."},
    { 'idPago' : 3, 'metodo': "Tarjeta de Debito", 'descripcion': "Pago con tarjetas que debitan directamente de la cuenta bancaria del titular."},
    { 'idPago' : 4, 'metodo': "Mercado Pago", 'descripcion': "Plataforma de pagos online"}
]

#### Definición de Categorías

Se definen las categorías a las que corresponderá cada producto.

In [5]:
categorias = [
    { 'idCategoria' : 1, 'categoria': 'Celulares'},
    { 'idCategoria' : 2, 'categoria': 'Notebooks'},
    { 'idCategoria' : 3, 'categoria': 'Tablets'},
    { 'idCategoria' : 4, 'categoria': 'Relojes'},
    { 'idCategoria' : 5, 'categoria': 'Auriculares'},
    { 'idCategoria' : 6, 'categoria': 'Parlantes'}
]

#### Definición de Productos

A continuación se detalla cada producto con sus características como costo, precio de venta, stock, etc. 

Posteriormente se definen los que serán nuestros productos estrella en la Tienda, estos serán los mejores productos en cuestión precio/calidad.

In [6]:
productos = [
    # Celulares (idCategoria = 1)
    {"idProducto": 1, "producto": "Samsung Galaxy A14", "idCategoria": 1, "costo": 180000, "precio": 240000, "stock": 35},
    {"idProducto": 2, "producto": "Samsung Galaxy A34", "idCategoria": 1, "costo": 230000, "precio": 310000, "stock": 28},
    {"idProducto": 3, "producto": "Samsung Galaxy S22", "idCategoria": 1, "costo": 420000, "precio": 550000, "stock": 15},
    {"idProducto": 4, "producto": "iPhone 11", "idCategoria": 1, "costo": 520000, "precio": 690000, "stock": 12},
    {"idProducto": 5, "producto": "iPhone 13", "idCategoria": 1, "costo": 680000, "precio": 850000, "stock": 10},
    {"idProducto": 6, "producto": "Motorola G32", "idCategoria": 1, "costo": 160000, "precio": 220000, "stock": 40},
    {"idProducto": 7, "producto": "Motorola Edge 30", "idCategoria": 1, "costo": 310000, "precio": 410000, "stock": 20},
    {"idProducto": 8, "producto": "Xiaomi Redmi Note 12", "idCategoria": 1, "costo": 190000, "precio": 260000, "stock": 32},

    # Notebooks (idCategoria = 2)
    {"idProducto": 9, "producto": "Notebook HP 15", "idCategoria": 2, "costo": 620000, "precio": 790000, "stock": 14},
    {"idProducto": 10, "producto": "Notebook Lenovo IdeaPad 3", "idCategoria": 2, "costo": 580000, "precio": 740000, "stock": 16},
    {"idProducto": 11, "producto": "Notebook Asus VivoBook", "idCategoria": 2, "costo": 640000, "precio": 820000, "stock": 12},
    {"idProducto": 12, "producto": "MacBook Air M1", "idCategoria": 2, "costo": 980000, "precio": 1250000, "stock": 6},
    {"idProducto": 13, "producto": "Notebook Dell Inspiron", "idCategoria": 2, "costo": 670000, "precio": 860000, "stock": 10},

    # Tablets (idCategoria = 3)
    {"idProducto": 14, "producto": "Samsung Galaxy Tab A8", "idCategoria": 3, "costo": 280000, "precio": 360000, "stock": 22},
    {"idProducto": 15, "producto": "Samsung Galaxy Tab S6 Lite", "idCategoria": 3, "costo": 350000, "precio": 450000, "stock": 18},
    {"idProducto": 16, "producto": "iPad 9na Generacion", "idCategoria": 3, "costo": 480000, "precio": 620000, "stock": 14},
    {"idProducto": 17, "producto": "iPad Air", "idCategoria": 3, "costo": 650000, "precio": 830000, "stock": 8},

    # Relojes (idCategoria = 4)
    {"idProducto": 18, "producto": "Smartwatch Samsung Galaxy Watch 4", "idCategoria": 4, "costo": 190000, "precio": 260000, "stock": 25},
    {"idProducto": 19, "producto": "Apple Watch Series 8", "idCategoria": 4, "costo": 420000, "precio": 560000, "stock": 9},
    {"idProducto": 20, "producto": "Xiaomi Mi Band 7", "idCategoria": 4, "costo": 65000, "precio": 95000, "stock": 50},
    {"idProducto": 21, "producto": "Smartwatch Amazfit GTS 4", "idCategoria": 4, "costo": 210000, "precio": 290000, "stock": 18},

    # Auriculares (idCategoria = 5)
    {"idProducto": 22, "producto": "Auriculares JBL Tune 510BT", "idCategoria": 5, "costo": 45000, "precio": 70000, "stock": 60},
    {"idProducto": 23, "producto": "Auriculares Sony WH-1000XM4", "idCategoria": 5, "costo": 220000, "precio": 290000, "stock": 11},
    {"idProducto": 24, "producto": "Auriculares Samsung Galaxy Buds 2", "idCategoria": 5, "costo": 120000, "precio": 165000, "stock": 24},
    {"idProducto": 25, "producto": "Auriculares Apple AirPods 2", "idCategoria": 5, "costo": 190000, "precio": 260000, "stock": 15},

    # Parlantes (idCategoria = 6)
    {"idProducto": 26, "producto": "Parlante JBL Go 3", "idCategoria": 6, "costo": 60000, "precio": 90000, "stock": 45},
    {"idProducto": 27, "producto": "Parlante JBL Charge 5", "idCategoria": 6, "costo": 210000, "precio": 280000, "stock": 17},
    {"idProducto": 28, "producto": "Parlante Sony SRS-XB13", "idCategoria": 6, "costo": 85000, "precio": 125000, "stock": 30},
    {"idProducto": 29, "producto": "Parlante Bose SoundLink Mini", "idCategoria": 6, "costo": 260000, "precio": 340000, "stock": 8}
]

In [7]:
productos_estrella = [
    "Samsung Galaxy A34",
    "Xiaomi Redmi Note 12",
    "Notebook Asus VivoBook",
    "Notebook HP 15",
    "Samsung Galaxy Tab A8",
    "Xiaomi Mi Band 7",
    "Auriculares JBL Tune 510BT",
    "Auriculares Samsung Galaxy Buds 2",
    "Parlante JBL Go 3"
]
#PRODUCTOS ESTRELLAS PORQUE TIENEN: Precio medio, alta rotación, no premium extremo, no gama baja absoluta

#### Generación de Clientes

Para cada cliente se crean los siguientes atributos:
* ID de Cliente
* Nombre y apellido
* Email
* Ciudad y Provincia
* Fecha de Registro

Para la generación de los clientes, vamos a definir las siguientes funciones:
* fecha_aleatoria --> Para generar la fechaRegistro del Cliente
* normalizar_texto --> Para normalizar mails
* generar_mail_unico --> Para garantizar mails unicos en el dataset.
* generar_clientes --> Para generar los clientes

In [8]:
# La siguiente funcion recibe dos fechas como parámetro y lo que hace es generar 
# una fecha aleatoria que se encuentre en el rango de fechas dadas 

def fecha_aleatoria(inicio, fin):
    delta = fin - inicio
    dias = random.randint(0, delta.days)
    return inicio + timedelta(days=dias) ## timedelta suma los dias calculados a la fecha inicio

In [9]:
# Set para almacenar emails ya generados (evita duplicados)
emails_existentes = set()

def normalizar_texto(texto):
    """ Esta función:
    - Convierte a minúsculas
    - Elimina tildes
    - Elimina la ñ
    - Elimina espacios
    - Elimina caracteres especiales
    Esto hace que el email sea más realista y válido.
    """
    texto = texto.lower()  # todo en minúscula
    texto = unicodedata.normalize('NFD', texto)  # Separa letras de acentos (ej: á -> a + ´)
    texto = ''.join(c for c in texto if unicodedata.category(c) != 'Mn') # Elimina los acentos (borra los caracteres de tipo "marca")
    texto = texto.replace(" ", "") # Elimina espacios
    return texto


def generar_email_unico(nombre, apellido):
    ##Genera un email único incluso si existen dos personas con el mismo nombre y apellido
    
    # Normalizamos nombre y apellido
    nombre_norm = normalizar_texto(nombre)
    apellido_norm = normalizar_texto(apellido)
    
    base = nombre_norm + apellido_norm
    dominio = random.choice(dominios)
    
    email = base + dominio
    contador = 1
    
    # Si el email ya existe, agregamos un número al final
    while email in emails_existentes:
        email = f"{base}{contador}{dominio}"
        contador += 1
    
    # Guardamos el email en el set para no repetirlo
    emails_existentes.add(email)
    
    return email

In [10]:
def generar_clientes(cantidad, inicio, fin, id_actual):
    lista_clientes = []
    id = id_actual

    for _ in range(cantidad):
        nombre = random.choice(nombres)
        apellido = random.choice(apellidos)
        provincia = random.choice(list(localidades.keys()))
        ciudad = random.choice(localidades[provincia])

        fecha = fecha_aleatoria(inicio, fin)

        cliente = {
            'idCliente': id,
            'nombre': nombre,
            'apellido': apellido,
            'email': generar_email_unico(nombre, apellido),
            'fechaRegistro': fecha,
            'provincia': provincia,
            'ciudad': ciudad
        }

        lista_clientes.append(cliente)
        id += 1

    return lista_clientes, id

In [11]:
# Hacemos la llamada a la función generar clientes que utiliza las llamadas a las demás funciones necesarias
# Se crea la lista de diccionarios clientes
clientes = []
id_Clientes = 1

#Se definen 326 clientes para el análisis de 2024
clientes_2024, id_Clientes = generar_clientes(326, fecha_inicio, datetime(2024,12,31), id_Clientes) 

clientes.extend(clientes_2024)

In [12]:
# verificamos que se hayan creado la cantidad de clientes definida
total_clientes= len(clientes)
print("Cantidad total de clientes 2024: ", total_clientes)

Cantidad total de clientes 2024:  326

### Generación de Ventas

Para la generación de las Ventas si bien vamos a usar funciones random, utilizaremos pesos en ciertas variables para que la funcion elija según mas probabilidades o menos.

Para eso tenemos que definir, pesos en:
* Categorias --> qué categorías son las que tienen mas probabilidad de ventas
* Mes --> hay meses que tienen tendencias a tener mayores ventas, por varios factores como Navidad por ejemplo

Tambien se definirá mas pesos para los productos estrella

Para la generación de las ventas se definen varias funciones:
* ajustar_pesos --> define los pesos finales para la elección del producto 
* generar_fecha_ponderadad --> genera la fecha de la transaccion teniendo en cuenta la fecha registro del cliente elegido y la fecha final del período de análisis
* elegir_producto --> elige el producto usando los pesos ajustados de la primer funcion
* calcular_cantidad --> calcula la cantidad de producto por cada transaccion dependiendo del precio
* generar_estado_pedido --> define el estado de cada pedido segun fecha de entrega
* generarVentas --> genera cada transaccion con las funciones anteriormente nombradas y con los datos de cantidad de ventas anual, el año, los clientes, los ids y los pesos de clientes que el primer año será 1 para todos, es decir, todos tienen la misma probabilidad de ser seleccionados

In [13]:
pesos_categoria = {
    1: 1.5,   # Celulares
    2: 1.4,   # Notebooks
    3: 0.8,   # Tablets
    4: 1.0,   # Relojes
    5: 1.6,   # Auriculares
    6: 1.2    # Parlantes
}
peso_mes = {
    1: 0.95,   # Enero - baja post fiestas
    2: 1.2,    # Inicio clases
    3: 1.2,    # Inicio clases fuerte
    4: 1,      # Mes normal
    5: 1,      # Mes normal
    6: 1.3,    # Aguinaldo
    7: 1.1,    # Vacaciones (depende rubro)
    8: 1,      # Mes normal
    9: 1.1,    # Empieza Q4
    10: 1.25,  # Día de la Madre
    11: 1.3,   # Cyber / Black Friday
    12: 1.35   # Navidad (máximo pico)
}

In [14]:
def ajustar_pesos(fecha, prod):
    # Peso base categoría
    peso = pesos_categoria[prod["idCategoria"]]

    # Estacionalidad general mes
    peso *= peso_mes[fecha.month]

    # INICIO DE CLASES (Feb/Mar)
    if fecha.month in [2, 3]:
        if prod["idCategoria"] in [2, 3]:  # Notebooks y Tablets
            peso *= 1.6
            
    # AGUINALDO (Jun/Jul)
    if fecha.month in [6, 7]:
        if prod["idCategoria"] == 2:  # Notebooks
            peso *= 1.5
        if prod["precio"] > 600000:  # Gama alta
            peso *= 1.3

    # DÍA DE LA MADRE (Oct)
    if fecha.month == 10:
        if prod["idCategoria"] in [4, 5]:  # Relojes y Auriculares
            peso *= 1.6
            
    # CYBER (Nov)
    if fecha.month == 11:
        if prod["precio"] < 300000:  # Productos masivos (mas baratos - mas cantidad)
            peso *= 1.5

    # NAVIDAD (Dic)
    if fecha.month == 12:
        if prod["idCategoria"] in [4, 5]:
            peso *= 1.8
        if prod["idCategoria"] == 1 and prod["precio"] < 400000:
            peso *= 1.4
            
    # Productos estrella
    if prod["producto"] in productos_estrella:
        peso *= 1.5

    return peso

In [15]:
def generar_fecha_ponderada(inicio, fin):
    
    combinaciones = []
    pesos = []
    
    for anio in range(inicio.year, fin.year + 1):
        for mes in range(1, 13):
            
            # Creamos fecha representativa del mes
            primer_dia = datetime(anio, mes, 1)
            ultimo_dia = datetime(anio, mes, calendar.monthrange(anio, mes)[1])

            if ultimo_dia >= inicio and primer_dia <= fin:
                
                combinaciones.append((anio, mes))
                peso_total = peso_mes[mes] 
                pesos.append(peso_total)
    
    # Elegimos combinación válida
    anio, mes = random.choices(combinaciones, weights=pesos)[0]
    
    # Día válido real
    ultimo_dia = calendar.monthrange(anio, mes)[1]
    dia = random.randint(1, ultimo_dia)
    
    fecha_final = datetime(anio, mes, dia)
    
    # Si el día quedó fuera del rango exacto, ajustamos
    if fecha_final < inicio:
        fecha_final = inicio
        
    if fecha_final > fin:
        fecha_final = fin
    
    return fecha_final

In [16]:
def elegirProducto(f):

    pesos_productos = []

    for prod in productos:
        peso = ajustar_pesos(f, prod)
        pesos_productos.append(peso)

    producto = random.choices(productos, weights=pesos_productos)[0]
    return producto

In [17]:
def calcular_cantidad(prod):
    precio = prod["precio"]

    # Económicos (menos de 200k)
    if precio < 200000:
        return random.choices([1, 2, 3], weights=[2, 4, 3])[0]

    # Intermedios (200k a 700k)
    elif precio < 700000:
        return random.choices([1, 2],weights=[5, 1])[0]

    # Premium (más de 700k)
    else:
        base = 1

    return base

In [18]:
def generar_estado_pedido(fecha_entrega):
    hoy = datetime(2026, 2, 1)  # simulamos cierre de análisis
    
    if fecha_entrega < hoy:
        return random.choices(["Entregado", "Cancelado"], weights=[93, 7])[0]
    else:
        return "Pendiente"

In [19]:
def generarVentas (cantidad_ventas, anio, clientes, idV, pesos_clientes):
    ventas_local = []
    inicio_anio = datetime(int(anio), 1, 1)
    fin_anio = datetime(int(anio), 12, 31)
    clientes_validos = [c for c in clientes if c['fechaRegistro'] <= fin_anio]

    pesos_validos = [pesos_clientes[clientes.index(c)] for c in clientes_validos]
    
    for i in range(1, cantidad_ventas+1):
        cliente_elegido = random.choices(clientes_validos, weights=pesos_validos)[0]
        idC = cliente_elegido['idCliente']
    
        fechaRegistro = cliente_elegido['fechaRegistro']  #tomamos la fecha de registro del cliente que debe ser anterior a la compra
        # la venta no puede ser antes del registro
        fecha_inicio_real = max(fechaRegistro, inicio_anio)
        
        fecha = generar_fecha_ponderada(fecha_inicio_real, fin_anio)
    
        producto = elegirProducto(fecha)
        idP = producto['idProducto']       #tomamos su id
        
        met = random.randint(0, len(metodosDePago)-1)     #elegimos un metodo de pago al azar
        idM = metodosDePago[met]['idPago']                #tomamos su id
        
        fecha_entrega = fecha + timedelta(days=random.randint(1, 10)) #le sumamos unos entre 1 a 10 dias a la fecha de entrega, el pedido no puede tardar mas de 10 dias
        cantidad = calcular_cantidad(producto)
        
        venta = {
            'idVenta' : idV, 
            'idCliente' : idC,
            'fechaTransaccion': fecha,
            'idProducto': idP,
            'cantidad' :  cantidad,
            'metodoPago' : idM,
            'estado' : generar_estado_pedido(fecha_entrega),
            'fechaEntrega' : fecha_entrega,
            'total': producto['precio'] * cantidad
        }
        ventas_local.append(venta)
        idV = idV+1
    return ventas_local, idV

In [20]:
# Hacemos el primer llamado a la función generar ventas con la lista de ventas ya creada,
# la cantidad de ventas ya definida para 2024 y los pesos con mismo valor para todos 
ventas = []
cantidad_2024 = 750
idVenta = 1
pesos_clientes = [1] * len(clientes_2024)

ventas2024, idVenta = generarVentas(cantidad_2024, "2024", clientes_2024, idVenta, pesos_clientes)

# chequeamos el número de ventas realizada
ventas += ventas2024
print("Cantidad de Ventas 2024: ", len(ventas))

Cantidad de Ventas 2024:  750

#### Fraccionar a clientes frecuentes

Ahora usaremos pandas para poder convertir ventas en una tabla y realizar lo siguiente:
* En compras_por_cliente agrupamos por cliente y ordenamos de mayor a menor
* Se toma el primer 20% de los clientes y se definen como frecuentes

Esto lo haremos para que la generación de ventas en 2025 tenga sentido en cuánto a clientes que compran frecuentemente en la Tienda.

In [21]:
dfVentas = pd.DataFrame(ventas)

In [22]:
compras_por_cliente = (
    dfVentas[dfVentas["fechaTransaccion"].dt.year == 2024]
    .groupby("idCliente")
    .size())

cantidad_frecuentes = int(len(clientes_2024) * 0.20)

clientes_frecuentes_ids = compras_por_cliente.sort_values(ascending=False) \
                                            .head(cantidad_frecuentes) \
                                            .index.tolist()

In [23]:
# Definimos la total de clientes de 2025
# Sacamos la diferencia con los clientes que ya teníamos

cantClientes_2025 = 595
cantidadNuevos = cantClientes_2025 - len(clientes_2024)

# Se hace la segunda llamada a generar_clientes para generar a los nuevos de 2025

clientesNuevos, id_Clientes = generar_clientes(cantidadNuevos, datetime(2025,1,1), fecha_fin, id_Clientes)
clientes.extend(clientesNuevos)

# Definimos pesos_base que usará numpy para intentar realizar una distribución pareto de los clientes
pesos_base = np.random.pareto(a = 2.5, size=len(clientes)) + 1

In [24]:
# El siguiente bucle le asigna un peso distinto a cada cliente
# dependiendo de la cantidad de compras de cada uno

for i, cliente in enumerate(clientes):
    idC = cliente["idCliente"]
    base = pesos_base[i]
    
    if idC in compras_por_cliente:
        compras_previas = compras_por_cliente[idC]
        peso = base * (1 + compras_previas * 0.3)
    else:
        peso = base
        
    pesos_clientes.append(peso)

In [25]:
# Hacemos el segundo llamado a generarVentas para la generación de las ventas 2025
# con 1352 ventas en el segundo año
cantidadVentas_2025 = 1352
ventas2025, idVenta = generarVentas(cantidadVentas_2025, "2025", clientes, idVenta, pesos_clientes)

ventas += ventas2025
df = pd.DataFrame(ventas)

# Observamos si la cantidad de ventas por año es la definida
print(df.groupby(df["fechaTransaccion"].dt.year).size())

fechaTransaccion
2024     750
2025    1352
dtype: int64

In [26]:
# Ventas totales 
len(ventas)

2102

#### Convertimos en tabla con Pandas

A continuación todas las lista serán convertidas en Dataframes que posteriormente serán exportados como archivos csv.

Entonces: 
* Se convierte en formato Dataframe cada lista
* Usando el método to_csv convertimos a csv
* El archivo se guarda en la misma carpeta donde tenemos nuestra Jupyter Notebook como csv

In [27]:
# Conversión a Dataframe
df_clientes = pd.DataFrame(clientes)
df_metodosDePago= pd.DataFrame(metodosDePago)
df_productos= pd.DataFrame(productos)
df_categorias= pd.DataFrame(categorias)
df_ventas = pd.DataFrame(ventas)

In [28]:
# Vemos los primeros registros de un dataframe, para ver si se creó bien
df_clientes.head() #nos muestra los primeros registros

,idCliente,nombre,apellido,email,fechaRegistro,provincia,ciudad
0,1,Monica,Garcia,monicagarcia@hotmail.com,2024-04-24,Entre Rios,Gualeguay
1,2,Silvia,Medina,silviamedina@gmail.com,2024-01-17,Chubut,Comodoro Rivadavia
2,3,Andrea,Ayala,andreaayala@gmail.com,2024-11-04,Mendoza,San Martin
3,4,Tamara,Farina,tamarafarina@yahoo.com,2024-10-28,Mendoza,Tunuyan
4,5,Sofia,Roldan,sofiaroldan@hotmail.com,2024-05-22,Salta,Tartagal

In [29]:
## Agregamos en la columna FechaTransaccion la hora de la transaccion
def agregar_hora(fecha):
    hora = random.randint(8, 22)   # rango de 8 a 22 hs
    minuto = random.randint(0, 59)
    segundo = random.randint(0, 59)
    return fecha.replace(hour=hora, minute=minuto, second=segundo)

df_ventas["fechaTransaccion"] = df_ventas["fechaTransaccion"].apply(agregar_hora)

In [30]:
# Verificamos que se hayan cargado bien los datos
df_ventas

,idVenta,idCliente,fechaTransaccion,idProducto,cantidad,metodoPago,estado,fechaEntrega,total
0,1,316,2024-09-12 14:12:21,2,1,3,Entregado,2024-09-20,310000
1,2,220,2024-12-25 17:21:40,24,3,4,Entregado,2024-12-28,495000
2,3,250,2024-10-13 18:53:30,2,1,2,Entregado,2024-10-19,310000
3,4,165,2024-10-09 08:35:27,24,3,1,Entregado,2024-10-12,495000
4,5,260,2024-09-12 20:05:59,23,1,2,Entregado,2024-09-22,290000
...,...,...,...,...,...,...,...,...,...
2097,2098,397,2025-09-28 08:08:55,14,1,2,Entregado,2025-10-03,360000
2098,2099,355,2025-09-19 15:22:58,4,1,2,Entregado,2025-09-20,690000
2099,2100,294,2025-06-10 21:31:59,10,1,1,Entregado,2025-06-13,740000
2100,2101,237,2025-01-01 12:42:20,4,1,3,Entregado,2025-01-03,690000
2101,2102,498,2025-08-28 12:51:17,11,1,3,Entregado,2025-09-06,820000

In [31]:
# Exportamos a csv

df_clientes.to_csv(
    "clientes.csv", #nombre del archivo
    index=False, #impide que se incluya el índice en el csv
    encoding="utf-8" # compatibilidad con caracteres especiales
)

In [32]:
df_metodosDePago.to_csv(
    "metodosDePago.csv",
    index=False,
    encoding="utf-8"
)

In [33]:
df_productos.to_csv(
    "productos.csv",
    index=False,
    encoding="utf-8"
)

In [34]:
df_ventas.to_csv(
    "ventas.csv",
    index=False,
    # encoding="utf-8"
)

In [35]:
df_categorias.to_csv(
    "categorias.csv",
    index=False,
    encoding="utf-8"
)

 ## Conclusión

Se generó un dataset sintético que simula las operaciones de un e-commerce de tecnología.

Este dataset permitirá analizar cuestion de negocio como:
* Productos más vendidos
* Categorías más rentables
* Distribución de ventas por ciudad
* Métodos de Pago más utilizados
* Comportamiento de compra de los clientes
* Análisis de stock mínimo por producto